services:
    app:
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            -  .:/var/www/html    
            -   type: bind
                source: /mnt/c/Users/Nadia/fet-results/timetables
                target: /var/www/html/storage/app/fet-results
                bind:
                    create_host_path: true
        environment:
            - WWWUSER=${UID:-1000}
        networks:
            - fetnet_laravel_net
        depends_on:
            mysql:
                condition: service_healthy
        build:
            context: .
            dockerfile: Dockerfile

    mysql:
        image: mysql:8.0
        container_name: mysql_fetnet
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: fetnet
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            TZ: Asia/Jakarta
        command:
            --default-authentication-plugin=mysql_native_password
            --skip-mysqlx
            --default-time-zone=Asia/Jakarta
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 10s
            retries: 10
        networks:
            - fetnet_laravel_net

    nginx:
        image: nginx:latest
        container_name: nginx_fetnet
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - fetnet_laravel_net

networks:
    fetnet_laravel_net:

volumes:
    mysql_data:
    fet_results:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /mnt/c/Users/Nadia/fet-results/timetables
