version: '3.8'

services:
    app:
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - /c/Users/LENOVO/fet-results/timetables:/var/www/html/storage/fet-xml
            - type: bind
              source: /mnt/c/Users/LENOVO/fet-results/timetables
              target: /var/www/html/storage/app/fet-results
        environment:
            - WWWUSER=${UID:-1000}
        networks:
            - fetnet_laravel_net
        depends_on:
            mysql:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M

    mysql:
        image: mysql:8.0
        container_name: mysql_fetnet
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: fetnet
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5

        networks:
            - fetnet_laravel_net
        deploy:
            resources:
                limits:
                    cpus: '0.30'
                    memory: 512M

    nginx:
        image: nginx:latest
        container_name: nginx_fetnet
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - fetnet_laravel_net
        deploy:
            resources:
                limits:
                    cpus: '0.20'
                    memory: 256M

networks:
    fetnet_laravel_net:
        driver: bridge

volumes:
    mysql_data:
    fet_results:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /mnt/c/Users/LENOVO/fet-results/timetables
