services:
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - fetnet_laravel_net
        depends_on:
            - mysql
        build:
            context: .
            dockerfile: Dockerfile


    mysql:
        image: mysql:8.0
        container_name: mysql_fetnet
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: fetnet
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - fetnet_laravel_net


    nginx:
        image: nginx:latest
        container_name: nginx_fetnet
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - fetnet_laravel_net


networks:
      fetnet_laravel_net:

volumes:
    mysql_data:
